### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by dismine** [mmamaev/timeboard#12]
Hi,

I tried to install your package with Python 3.8. I saw that it was not tested for support Python 3.8, but things even worse for me. I couldn't install it because of blocked dependency.

Here is your current requirements.txt:
```
pandas >=0.22,<=0.24; python_version < '3.6.1'
pandas >=0.22; python_version >= '3.6.1'
numpy >=1.13,<=1.16; python_version < '3.6'
numpy >=1.16; python_version >= '3.6'
python-dateutil>=2.6.1
six
```
On my system installed: 
```
python --version
Python 3.6.9
```
But if i use `pipdeptree` to check for requirements i see:
```
pipdeptree -r -p pandas
pandas==0.24.0
  - timeboard==0.2.3 [requires: pandas>=0.22,<=0.24]
```
Where it should say `pandas >=0.22` since I use Python 3.6.9.

I believe in your `requirements.txt` you have made a mistake. According to [PEP 508 Environment Markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) `python_version` resolves as **3.6** in my case. Where if you want full version info you should use `python_full_version`. Which will correctly resolve to **3.6.9** in my case.

**Comment by mmamaev** [comment]
Thank you, I changed `python_version` to `python_full_version` where 3.6.1 is mentioned. I tested the new requirements.txt with 3.6.9, it works. 

But with python 3.8 you should not have had any problems. I added 3.8 to Travis and Appveyor builds, they pass.

**Comment by dismine** [comment]
Thank you! :man_dancing: 

> But with python 3.8 you should not have had any problems. I added 3.8 to Travis and Appveyor builds, they pass.

It is the installing problem we are talking about. It is highly possible that some other project requires version of a package timeboard doesn't allow to install in my case. If no other package in a way it will work.
