### ISSUE TITLE
User holiday (Annual Leave)

### ISSUE THREAD

**Issue by alan1world** [mmamaev/timeboard#2]
Hi, 
I notice when generating calenders you can mark particular days as holidays. In this case all staff would be off.
Is there the functionality to mark a specific employee as holiday on a specific day?
Thanks.

**Comment by mmamaev** [comment]
Calendar (timeboard) shows when the organization is doing business as a whle.  

An individual employee may enter and leave the organization at any time. In [Common Use Cases](https://timeboard.readthedocs.io/en/latest/use_cases.html#Average-annual-headcount) we use a simple model with an employee's tenure being one uninterrupted period of time.  In real life, of course, an employee takes annual leaves, sick leaves, etc.  Therefore, a tenure has to be represented by a sequence of intervals which are recorded somewhere in your personnel register. In any case, the implementation of this register is external to timeboard. When you need to do calendar calculations, you extract the dates from the register and feed them into timeboard, as we have done in the examples in the docs.
