### ISSUE TITLE
Future warnings

### ISSUE THREAD

**Issue by gadgetmind** [mmamaev/timeboard#7]
I just upgraded to Python 3,6, and installed timeboard to go with this, and am now getting -

FutureWarning: Creating a PeriodIndex by passing range endpoints is deprecated.  Use `pandas.period_range` instead.
timeboard/calendars/calendarbase.py:51: 
timeboard/calendars/calendarbase.py:68: 
timeboard/core.py:228: 
timeboard/core.py:510:

and -
numpy/core/fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead

I'm not sure which component has changed to cause this, but I guess pandas. The latter one looks like a mismatch between pandas and numpy, but the first ones suggest changes required in timeboard?

**Comment by mmamaev** [comment]
You're right. Pandas is introducing breaking changes to API. so we've got this FutureWarnings with pandas 0.24. I will fix them in the next release of timeboard.

**Comment by mmamaev** [comment]
timeboard 0.2.3 is compatible with pandas 1.0
